services:
  - type: web
    name: healthmate-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker --chdir backend main:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
      - key: ENV
        value: production
      - key: FAISS_DIR
        value: /data/faiss_indexes
      - key: GROQ_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GMAIL_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
    disk:
      name: faiss-storage
      mountPath: /data/faiss_indexes
      sizeGB: 1
